import { useState, useEffect, useRef } from "react";
import { useParams, useNavigate } from "react-router";
import {
  ArrowLeft,
  Globe,
  Clock,
  CalendarDays,
  Users,
  Swords,
  ScrollText,
  Brain,
  Send,
  Lock,
  Eye,
  ChevronDown,
  Zap,
  CheckCircle2,
  AlertTriangle,
  Info,
  Radio,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

// ─── Mock Data ────────────────────────────────────────────────────────────────

const MOCK_INCIDENTS = {
  1: {
    id: 1,
    title: "API Service Down",
    service: "api.acme.com",
    severity: "P1",
    status: "Active",
    source: "UptimeRobot",
    affectedUrl: "https://api.acme.com",
    startedAt: "May 20, 2026 10:21 AM",
    resolvedAt: null,
    duration: "00:23:41",
    responders: [
      { initials: "MU", name: "Mustafa", role: "Lead", color: "bg-violet-900/80 text-violet-200" },
      { initials: "AL", name: "Ali", role: "Support", color: "bg-blue-900/80 text-blue-200" },
      { initials: "SA", name: "Sara", role: "Support", color: "bg-emerald-900/80 text-emerald-200" },
    ],
    affectedServices: [
      { name: "Payment API", status: "down" },
      { name: "Auth Service", status: "degraded" },
    ],
    aiRootCause: [
      "Database connection pool exhausted — max connections reached under load",
      "Recent deployment (v2.3.1) introduced unoptimized query in /api/payments",
      "Third-party payment gateway timeout causing retry storm",
    ],
    postmortemStatus: null,
    timeline: [
      { id: 1, type: "system", message: "Incident auto-created via UptimeRobot — site unreachable", time: "10:21 AM", isPublic: true },
      { id: 2, type: "system", message: "Severity auto-detected as P1 — error rate exceeded threshold", time: "10:21 AM", isPublic: false },
      { id: 3, type: "manual", author: "MU", name: "Mustafa", message: "On it — checking DB connection pool and recent deployments", time: "10:24 AM", isPublic: false },
      { id: 4, type: "manual", author: "AL", name: "Ali", message: "Confirmed high error rate on /api/payments — traces showing DB timeout", time: "10:28 AM", isPublic: false },
      { id: 5, type: "system", message: "Status updated to Identified", time: "10:30 AM", isPublic: true },
      { id: 6, type: "manual", author: "MU", name: "Mustafa", message: "Rolled back v2.3.1 deployment — monitoring now", time: "10:35 AM", isPublic: true },
    ],
  },
  3: {
    id: 3,
    title: "File Upload Failing",
    service: "uploads.acme.com",
    severity: "P3",
    status: "Resolved",
    source: "Manual",
    affectedUrl: "https://uploads.acme.com",
    startedAt: "May 19, 2026 08:40 PM",
    resolvedAt: "May 19, 2026 09:45 PM",
    duration: "01:05:32",
    responders: [
      { initials: "MU", name: "Mustafa", role: "Lead", color: "bg-violet-900/80 text-violet-200" },
    ],
    affectedServices: [
      { name: "Upload Service", status: "down" },
    ],
    aiRootCause: [
      "S3 bucket policy misconfiguration after IAM role update",
      "Missing PutObject permission for uploads.acme.com service account",
    ],
    postmortemStatus: "generated",
    timeline: [
      { id: 1, type: "system", message: "Incident created manually by Mustafa", time: "08:40 PM", isPublic: true },
      { id: 2, type: "manual", author: "MU", name: "Mustafa", message: "S3 bucket permissions look off after the IAM role update earlier today", time: "08:45 PM", isPublic: false },
      { id: 3, type: "system", message: "Status updated to Identified", time: "08:50 PM", isPublic: true },
      { id: 4, type: "manual", author: "MU", name: "Mustafa", message: "Permissions corrected and deployed — testing uploads now", time: "09:40 PM", isPublic: true },
      { id: 5, type: "system", message: "Status updated to Resolved", time: "09:45 PM", isPublic: true },
      { id: 6, type: "system", message: "Postmortem generated by AI", time: "09:46 PM", isPublic: false },
    ],
  },
};

// ─── Style maps ───────────────────────────────────────────────────────────────

const severityClasses = {
  P1: "bg-red-950/70 text-red-200 border border-red-800/80",
  P2: "bg-orange-950/60 text-orange-200 border border-orange-800/70",
  P3: "bg-emerald-950/60 text-emerald-200 border border-emerald-800/70",
};

const statusClasses = {
  Active: "bg-red-950/70 text-red-200 border border-red-800/80",
  Monitoring: "bg-orange-950/60 text-orange-200 border border-orange-800/70",
  Resolved: "bg-emerald-950/60 text-emerald-200 border border-emerald-800/70",
  Identified: "bg-purple-950/60 text-purple-200 border border-purple-800/70",
  Investigating: "bg-blue-950/60 text-blue-200 border border-blue-800/70",
};

const serviceStatusDot = {
  down: "bg-red-500",
  degraded: "bg-orange-400",
  operational: "bg-emerald-500",
};

const dropdownContentClass =
  "w-44 border border-zinc-700 bg-zinc-950 text-zinc-100 [&_[data-slot=dropdown-menu-radio-item]]:focus:bg-zinc-800 [&_[data-slot=dropdown-menu-radio-item]]:focus:text-zinc-100";

// ─── Live Timer ───────────────────────────────────────────────────────────────

function LiveTimer({ startedAt, isActive }) {
  const [elapsed, setElapsed] = useState("00:00:00");

  useEffect(() => {
    if (!isActive) return;
    const start = new Date(startedAt).getTime();
    const tick = () => {
      const diff = Math.floor((Date.now() - start) / 1000);
      const h = String(Math.floor(diff / 3600)).padStart(2, "0");
      const m = String(Math.floor((diff % 3600) / 60)).padStart(2, "0");
      const s = String(diff % 60).padStart(2, "0");
      setElapsed(`${h}:${m}:${s}`);
    };
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, [startedAt, isActive]);

  return (
    <span className={`font-mono text-sm ${isActive ? "text-orange-400" : "text-zinc-400"}`}>
      {isActive ? elapsed : "01:05:32"}
    </span>
  );
}

// ─── Timeline Event ───────────────────────────────────────────────────────────

function TimelineEvent({ event }) {
  const isSystem = event.type === "system";

  return (
    <div className="flex gap-3">
      {/* Icon / Avatar */}
      <div className="flex flex-col items-center">
        <div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-bold
          ${isSystem ? "bg-zinc-800 text-zinc-500" : "bg-violet-900/80 text-violet-200"}`}>
          {isSystem ? <Zap className="size-3" /> : event.author}
        </div>
        <div className="mt-1 w-px flex-1 bg-zinc-800" />
      </div>

      {/* Content */}
      <div className="pb-5 flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1">
          {!isSystem && (
            <span className="text-xs font-semibold text-zinc-300">{event.name}</span>
          )}
          <span className="text-[11px] text-zinc-600">{event.time}</span>
          {/* public / internal tag */}
          <span className={`ml-auto flex items-center gap-1 text-[10px] rounded px-1.5 py-0.5
            ${event.isPublic ? "bg-emerald-950/60 text-emerald-400" : "bg-zinc-800 text-zinc-500"}`}>
            {event.isPublic ? <Eye className="size-2.5" /> : <Lock className="size-2.5" />}
            {event.isPublic ? "Public" : "Internal"}
          </span>
        </div>
        <p className={`text-sm leading-relaxed ${isSystem ? "text-zinc-500 italic" : "text-zinc-300"}`}>
          {event.message}
        </p>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function IncidentDetail() {
  const { incidentId } = useParams();
  const navigate = useNavigate();
  const feedRef = useRef(null);

  const incident = MOCK_INCIDENTS[incidentId] ?? MOCK_INCIDENTS[1];
  const isActive = incident.status !== "Resolved";

  const [status, setStatus] = useState(incident.status);
  const [timeline, setTimeline] = useState(incident.timeline);
  const [update, setUpdate] = useState("");
  const [isPublic, setIsPublic] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiDone, setAiDone] = useState(!!incident.aiRootCause);

  // Auto scroll timeline to bottom
  useEffect(() => {
    if (feedRef.current) {
      feedRef.current.scrollTop = feedRef.current.scrollHeight;
    }
  }, [timeline]);

  const handlePostUpdate = () => {
    if (!update.trim()) return;
    const newEvent = {
      id: Date.now(),
      type: "manual",
      author: "MU",
      name: "Mustafa",
      message: update,
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      isPublic,
    };
    setTimeline((prev) => [...prev, newEvent]);
    setUpdate("");
  };

  const handleStatusChange = (val) => {
    setStatus(val);
    const newEvent = {
      id: Date.now(),
      type: "system",
      message: `Status updated to ${val}`,
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      isPublic: true,
    };
    setTimeline((prev) => [...prev, newEvent]);
  };

  const handleGenerateAI = () => {
    setAiLoading(true);
    setTimeout(() => { setAiLoading(false); setAiDone(true); }, 2000);
  };

  return (
    <div className="flex flex-col gap-0">

      {/* ── Back + Action bar ─────────────────────────────────────────────── */}
      <div className="flex items-center justify-between gap-4 border-b border-zinc-800 pb-4 mb-6">
        <button
          onClick={() => navigate("/dashboard/incidents")}
          className="flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-200 transition-colors"
        >
          <ArrowLeft className="size-4" />
          Back to Incidents
        </button>
        <div className="flex items-center gap-2">
          {isActive && (
            <button
              onClick={() => navigate(`/dashboard/war-room/${incidentId}`)}
              className="flex items-center gap-2 rounded-md bg-red-950/60 border border-red-800/60 px-3 py-1.5 text-xs font-semibold text-red-200 hover:bg-red-900/60 transition-colors"
            >
              <Swords className="size-3.5" />
              Open War Room
            </button>
          )}
          {!isActive && (
            <button
              onClick={() => navigate(`/dashboard/incidents/${incidentId}/postmortem`)}
              className="flex items-center gap-2 rounded-md bg-violet-950/60 border border-violet-800/60 px-3 py-1.5 text-xs font-semibold text-violet-200 hover:bg-violet-900/60 transition-colors"
            >
              <ScrollText className="size-3.5" />
              View Postmortem
            </button>
          )}
        </div>
      </div>

      {/* ── Incident Header ───────────────────────────────────────────────── */}
      <div className="mb-6 flex flex-col gap-3">
        {/* Title row */}
        <div className="flex items-start gap-3 flex-wrap">
          {isActive && (
            <span className="relative flex h-2.5 w-2.5 shrink-0 mt-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-500 opacity-75" />
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-red-500" />
            </span>
          )}
          <h1 className="text-2xl font-bold text-zinc-100 leading-tight flex-1">
            {incident.title}
          </h1>
          <div className="flex items-center gap-2 shrink-0">
            <span className={`rounded-md px-2.5 py-1 text-xs font-bold ${severityClasses[incident.severity]}`}>
              {incident.severity}
            </span>
            {/* Status dropdown */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button className={`inline-flex items-center gap-1 rounded-md px-2.5 py-1 text-xs font-bold outline-none ${statusClasses[status]}`}>
                  {status}
                  <ChevronDown className="size-3 opacity-70" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className={dropdownContentClass}>
                <DropdownMenuGroup>
                  <DropdownMenuLabel className="text-zinc-400">Change Status</DropdownMenuLabel>
                  <DropdownMenuRadioGroup value={status} onValueChange={handleStatusChange}>
                    {["Active", "Investigating", "Identified", "Monitoring", "Resolved"].map((s) => (
                      <DropdownMenuRadioItem key={s} value={s} className="gap-2">
                        <span className={`size-2 shrink-0 rounded-full ${
                          s === "Active" ? "bg-red-600" :
                          s === "Monitoring" ? "bg-orange-500" :
                          s === "Investigating" ? "bg-blue-500" :
                          s === "Identified" ? "bg-purple-500" : "bg-emerald-500"
                        }`} />
                        {s}
                      </DropdownMenuRadioItem>
                    ))}
                  </DropdownMenuRadioGroup>
                </DropdownMenuGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        {/* Meta row */}
        <div className="flex flex-wrap items-center gap-5 text-xs text-zinc-500">
          <span className="flex items-center gap-1.5">
            <Globe className="size-3" /> {incident.service}
          </span>
          <span className="flex items-center gap-1.5">
            <CalendarDays className="size-3" /> {incident.startedAt}
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="size-3" />
            <LiveTimer startedAt={incident.startedAt} isActive={isActive} />
          </span>
          <span className="flex items-center gap-1.5">
            <Radio className="size-3" /> Source: {incident.source}
          </span>
          {incident.resolvedAt && (
            <span className="flex items-center gap-1.5 text-emerald-500">
              <CheckCircle2 className="size-3" /> Resolved: {incident.resolvedAt}
            </span>
          )}
        </div>
      </div>

      {/* ── Two column layout ─────────────────────────────────────────────── */}
      <div className="flex flex-col lg:flex-row gap-6">

        {/* LEFT — Timeline (60%) */}
        <div className="flex flex-col gap-4 lg:w-[60%]">
          <div className="rounded-lg border border-zinc-800 bg-zinc-950">

            {/* Timeline header */}
            <div className="flex items-center justify-between border-b border-zinc-800 px-4 py-3">
              <h2 className="text-sm font-semibold text-zinc-200">Timeline</h2>
              <span className="text-xs text-zinc-600">{timeline.length} events</span>
            </div>

            {/* Events */}
            <div ref={feedRef} className="max-h-[480px] overflow-y-auto px-4 pt-4">
              {timeline.map((event) => (
                <TimelineEvent key={event.id} event={event} />
              ))}
            </div>

            {/* Update composer */}
            <div className="border-t border-zinc-800 p-4 flex flex-col gap-3">
              <textarea
                value={update}
                onChange={(e) => setUpdate(e.target.value)}
                placeholder="Post an update to the timeline..."
                rows={2}
                className="w-full resize-none rounded-md border border-zinc-700 bg-zinc-900 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-600 outline-none focus:border-zinc-600 transition-colors"
              />
              <div className="flex items-center justify-between">
                {/* Public / Internal toggle */}
                <button
                  onClick={() => setIsPublic((p) => !p)}
                  className={`flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium transition-colors
                    ${isPublic ? "bg-emerald-950/60 text-emerald-300 border border-emerald-800/60" : "bg-zinc-800 text-zinc-400 border border-zinc-700"}`}
                >
                  {isPublic ? <Eye className="size-3" /> : <Lock className="size-3" />}
                  {isPublic ? "Public" : "Internal"}
                </button>
                <button
                  onClick={handlePostUpdate}
                  className="flex items-center gap-2 rounded-md border border-zinc-700 bg-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-100 hover:bg-zinc-700 transition-colors"
                >
                  <Send className="size-3" />
                  Post Update
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT — Info Panel (40%) */}
        <div className="flex flex-col gap-4 lg:w-[40%]">

          {/* Details card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <h2 className="text-sm font-semibold text-zinc-200 border-b border-zinc-800 pb-2">Details</h2>
            {[
              { label: "Incident ID", value: `INC-00${incident.id}` },
              { label: "Source", value: incident.source },
              { label: "Affected URL", value: incident.affectedUrl },
              { label: "Severity", value: incident.severity },
            ].map(({ label, value }) => (
              <div key={label} className="flex items-center justify-between text-xs">
                <span className="text-zinc-500">{label}</span>
                <span className="text-zinc-300 font-medium">{value}</span>
              </div>
            ))}
          </div>

          {/* Responders card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-2">
              <h2 className="text-sm font-semibold text-zinc-200">Responders</h2>
              <Users className="size-3.5 text-zinc-600" />
            </div>
            {incident.responders.map((r) => (
              <div key={r.initials} className="flex items-center gap-3">
                <div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${r.color}`}>
                  {r.initials}
                </div>
                <div className="flex-1">
                  <p className="text-xs font-medium text-zinc-200">{r.name}</p>
                  <p className="text-[11px] text-zinc-600">{r.role}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Affected Services card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <h2 className="text-sm font-semibold text-zinc-200 border-b border-zinc-800 pb-2">Affected Services</h2>
            {incident.affectedServices.map((s) => (
              <div key={s.name} className="flex items-center justify-between">
                <span className="text-xs text-zinc-300">{s.name}</span>
                <div className="flex items-center gap-1.5">
                  <span className={`h-2 w-2 rounded-full ${serviceStatusDot[s.status]}`} />
                  <span className="text-[11px] text-zinc-500 capitalize">{s.status}</span>
                </div>
              </div>
            ))}
          </div>

          {/* AI Root Cause card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-2">
              <div className="flex items-center gap-2">
                <Brain className="size-3.5 text-violet-400" />
                <h2 className="text-sm font-semibold text-zinc-200">AI Root Cause</h2>
              </div>
              {!aiDone && !aiLoading && (
                <button
                  onClick={handleGenerateAI}
                  className="text-[11px] text-violet-400 hover:text-violet-300 transition-colors"
                >
                  Analyse →
                </button>
              )}
              {aiDone && (
                <button
                  onClick={handleGenerateAI}
                  className="text-[11px] text-zinc-600 hover:text-zinc-400 transition-colors"
                >
                  Regenerate
                </button>
              )}
            </div>

            {aiLoading && (
              <div className="flex items-center gap-2 text-xs text-zinc-500">
                <span className="animate-pulse">Analysing incident data...</span>
              </div>
            )}

            {aiDone && !aiLoading && (
              <ol className="flex flex-col gap-2.5">
                {incident.aiRootCause.map((cause, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-zinc-400">
                    <span className="shrink-0 mt-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-violet-950/80 text-[9px] font-bold text-violet-300">
                      {i + 1}
                    </span>
                    {cause}
                  </li>
                ))}
              </ol>
            )}

            {!aiDone && !aiLoading && (
              <p className="text-xs text-zinc-600 italic">
                Click "Analyse" to generate probable root causes for this incident.
              </p>
            )}
          </div>

          {/* Postmortem card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <div className="flex items-center gap-2 border-b border-zinc-800 pb-2">
              <ScrollText className="size-3.5 text-zinc-500" />
              <h2 className="text-sm font-semibold text-zinc-200">Postmortem</h2>
            </div>
            {incident.postmortemStatus === "generated" ? (
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs text-emerald-400">
                  <CheckCircle2 className="size-3.5" />
                  Generated
                </div>
                <button
                  onClick={() => navigate(`/dashboard/incidents/${incidentId}/postmortem`)}
                  className="text-[11px] text-violet-400 hover:text-violet-300 transition-colors"
                >
                  View →
                </button>
              </div>
            ) : isActive ? (
              <div className="flex items-center gap-2 text-xs text-zinc-600">
                <Info className="size-3.5" />
                Available after incident is resolved
              </div>
            ) : (
              <button
                onClick={() => navigate(`/dashboard/incidents/${incidentId}/postmortem`)}
                className="w-full rounded-md border border-zinc-700 bg-zinc-800 px-3 py-2 text-xs font-medium text-zinc-100 hover:bg-zinc-700 transition-colors flex items-center justify-center gap-2"
              >
                <Brain className="size-3.5 text-violet-400" />
                Generate with AI
              </button>
            )}
          </div>

        </div>
      </div>
    </div>
  );
}