import { useState } from "react";
import { useParams, useNavigate } from "react-router";
import {
  ArrowLeft,
  Brain,
  ScrollText,
  Clock,
  CalendarDays,
  Globe,
  Users,
  CheckSquare,
  CheckCircle2,
  Square,
  ChevronDown,
  ChevronUp,
  Sparkles,
  RefreshCw,
  FileDown,
  Send,
  Zap,
  Eye,
  Lock,
  AlertTriangle,
  ThumbsUp,
  ThumbsDown,
  Plus,
  X,
} from "lucide-react";

// ─── Mock Data ────────────────────────────────────────────────────────────────

const MOCK_POSTMORTEMS = {
  3: {
    incidentId: 3,
    title: "File Upload Failing",
    service: "uploads.acme.com",
    severity: "P3",
    startedAt: "May 19, 2026 08:40 PM",
    resolvedAt: "May 19, 2026 09:45 PM",
    duration: "01:05:32",
    status: "Draft", // Draft | In Review | Published
    lead: { initials: "MU", name: "Mustafa", color: "bg-violet-900/80 text-violet-200" },
    responders: [
      { initials: "MU", name: "Mustafa", color: "bg-violet-900/80 text-violet-200" },
    ],
    summary:
      "An S3 bucket policy misconfiguration introduced during an IAM role update caused all file uploads to fail for approximately 65 minutes. The issue was identified by the on-call engineer and resolved by correcting the PutObject permissions for the uploads service account.",
    timeline: [
      { id: 1, type: "system", message: "Incident created manually by Mustafa", time: "08:40 PM", isPublic: true },
      { id: 2, type: "manual", author: "MU", name: "Mustafa", message: "S3 bucket permissions look off after the IAM role update earlier today", time: "08:45 PM", isPublic: false },
      { id: 3, type: "system", message: "Status updated to Identified", time: "08:50 PM", isPublic: true },
      { id: 4, type: "manual", author: "MU", name: "Mustafa", message: "Permissions corrected and deployed — testing uploads now", time: "09:40 PM", isPublic: true },
      { id: 5, type: "system", message: "Status updated to Resolved", time: "09:45 PM", isPublic: true },
      { id: 6, type: "system", message: "Postmortem generated by AI", time: "09:46 PM", isPublic: false },
    ],
    rootCause: [
      "IAM role update removed the PutObject permission from the uploads.acme.com service account",
      "No automated policy validation ran after the IAM change — the misconfiguration was not caught pre-deployment",
      "Lack of integration test covering S3 write permissions on deployment pipeline",
    ],
    impact:
      "100% of file upload requests failed during the 65-minute window. Approximately 340 users were affected. No data was lost — uploads were rejected at the API layer before reaching S3.",
    wentWell: [
      "On-call engineer identified the root cause quickly after checking IAM logs",
      "Fix was simple — no code change required, only a permissions update",
      "Clear runbook for IAM changes was available and followed to verify the fix",
    ],
    wentWrong: [
      "No automated check validated S3 permissions after the IAM role update",
      "Initial alert was not specific enough — just reported upload failures without pointing to S3",
      "No staging environment test covered this IAM permission path",
    ],
    actionItems: [
      { id: 1, text: "Add automated S3 permission validation to deployment pipeline", assignee: "Mustafa", done: false },
      { id: 2, text: "Improve alert messaging to include affected AWS resource context", assignee: "Ali", done: false },
      { id: 3, text: "Create integration test for upload service S3 write access", assignee: null, done: false },
      { id: 4, text: "Add IAM change review step to team runbook", assignee: "Mustafa", done: true },
    ],
  },
};

// ─── Style maps ───────────────────────────────────────────────────────────────

const severityClasses = {
  P1: "bg-red-950/70 text-red-200 border border-red-800/80",
  P2: "bg-orange-950/60 text-orange-200 border border-orange-800/70",
  P3: "bg-emerald-950/60 text-emerald-200 border border-emerald-800/70",
};

const postmortemStatusClasses = {
  Draft: "bg-zinc-800 text-zinc-400 border border-zinc-700",
  "In Review": "bg-orange-950/60 text-orange-200 border border-orange-800/70",
  Published: "bg-emerald-950/60 text-emerald-200 border border-emerald-800/70",
};

const STATUS_FLOW = ["Draft", "In Review", "Published"];

// ─── Section wrapper ──────────────────────────────────────────────────────────

function Section({ icon: Icon, iconClass = "text-zinc-500", title, badge, children, defaultOpen = true }) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-950 overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((p) => !p)}
        className="flex w-full items-center justify-between gap-3 px-5 py-4 text-left hover:bg-zinc-900/40 transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <Icon className={`size-4 shrink-0 ${iconClass}`} />
          <span className="text-sm font-semibold text-zinc-200">{title}</span>
          {badge && (
            <span className="rounded-full bg-zinc-800 px-2 py-0.5 text-[10px] text-zinc-500 font-medium">
              {badge}
            </span>
          )}
        </div>
        {open ? (
          <ChevronUp className="size-3.5 text-zinc-600 shrink-0" />
        ) : (
          <ChevronDown className="size-3.5 text-zinc-600 shrink-0" />
        )}
      </button>
      {open && <div className="border-t border-zinc-800 px-5 py-4">{children}</div>}
    </div>
  );
}

// ─── Editable text block ──────────────────────────────────────────────────────

function EditableBlock({ value, onChange, placeholder, rows = 4 }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(value);

  const save = () => {
    onChange(draft);
    setEditing(false);
  };

  const cancel = () => {
    setDraft(value);
    setEditing(false);
  };

  if (editing) {
    return (
      <div className="flex flex-col gap-2">
        <textarea
          autoFocus
          rows={rows}
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          className="w-full resize-none rounded-md border border-zinc-700 bg-zinc-900 px-3 py-2.5 text-sm text-zinc-200 leading-relaxed placeholder:text-zinc-600 outline-none focus:border-zinc-600 transition-colors"
          placeholder={placeholder}
        />
        <div className="flex items-center gap-2 justify-end">
          <button
            onClick={cancel}
            className="text-xs text-zinc-600 hover:text-zinc-400 transition-colors px-2 py-1"
          >
            Cancel
          </button>
          <button
            onClick={save}
            className="flex items-center gap-1.5 rounded-md border border-zinc-700 bg-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-100 hover:bg-zinc-700 transition-colors"
          >
            <Send className="size-3" />
            Save
          </button>
        </div>
      </div>
    );
  }

  return (
    <button
      type="button"
      onClick={() => setEditing(true)}
      className="group w-full text-left"
    >
      <p className="text-sm text-zinc-400 leading-relaxed group-hover:text-zinc-300 transition-colors">
        {value || <span className="text-zinc-600 italic">{placeholder}</span>}
      </p>
      <p className="mt-2 text-[11px] text-zinc-700 group-hover:text-zinc-600 transition-colors">
        Click to edit
      </p>
    </button>
  );
}

// ─── Bullet list editor ───────────────────────────────────────────────────────

function BulletListEditor({ items, onChange, icon: Icon, iconClass, emptyLabel }) {
  const [adding, setAdding] = useState(false);
  const [newText, setNewText] = useState("");

  const add = () => {
    if (!newText.trim()) return;
    onChange([...items, newText.trim()]);
    setNewText("");
    setAdding(false);
  };

  const remove = (i) => onChange(items.filter((_, idx) => idx !== i));

  return (
    <div className="flex flex-col gap-2">
      {items.length === 0 && !adding && (
        <p className="text-xs text-zinc-600 italic">{emptyLabel}</p>
      )}
      {items.map((item, i) => (
        <div key={i} className="group flex items-start gap-2.5">
          <Icon className={`size-3.5 shrink-0 mt-0.5 ${iconClass}`} />
          <p className="flex-1 text-sm text-zinc-400 leading-relaxed">{item}</p>
          <button
            onClick={() => remove(i)}
            className="opacity-0 group-hover:opacity-100 text-zinc-700 hover:text-zinc-400 transition-all shrink-0 mt-0.5"
          >
            <X className="size-3.5" />
          </button>
        </div>
      ))}

      {adding ? (
        <div className="flex items-center gap-2 mt-1">
          <input
            autoFocus
            value={newText}
            onChange={(e) => setNewText(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") add();
              if (e.key === "Escape") { setAdding(false); setNewText(""); }
            }}
            placeholder="Add item..."
            className="flex-1 rounded-md border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 outline-none focus:border-zinc-600 transition-colors"
          />
          <button onClick={add} className="text-zinc-400 hover:text-zinc-200">
            <Send className="size-3.5" />
          </button>
          <button onClick={() => { setAdding(false); setNewText(""); }} className="text-zinc-700 hover:text-zinc-400">
            <X className="size-3.5" />
          </button>
        </div>
      ) : (
        <button
          onClick={() => setAdding(true)}
          className="flex items-center gap-1.5 text-xs text-zinc-700 hover:text-zinc-500 transition-colors mt-1"
        >
          <Plus className="size-3.5" />
          Add item
        </button>
      )}
    </div>
  );
}

// ─── Action Items ─────────────────────────────────────────────────────────────

function ActionItems({ items, onChange }) {
  const [adding, setAdding] = useState(false);
  const [newText, setNewText] = useState("");
  const [newAssignee, setNewAssignee] = useState("");

  const toggle = (id) =>
    onChange(items.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));

  const remove = (id) => onChange(items.filter((t) => t.id !== id));

  const add = () => {
    if (!newText.trim()) return;
    onChange([
      ...items,
      { id: Date.now(), text: newText.trim(), assignee: newAssignee.trim() || null, done: false },
    ]);
    setNewText("");
    setNewAssignee("");
    setAdding(false);
  };

  const done = items.filter((t) => t.done).length;

  return (
    <div className="flex flex-col gap-2">
      {/* Progress */}
      <div className="flex items-center gap-3 mb-2">
        <div className="flex-1 h-1 rounded-full bg-zinc-800">
          <div
            className="h-1 rounded-full bg-emerald-600 transition-all duration-500"
            style={{ width: items.length ? `${(done / items.length) * 100}%` : "0%" }}
          />
        </div>
        <span className="text-[11px] text-zinc-600 shrink-0">{done}/{items.length} done</span>
      </div>

      {items.map((item) => (
        <div
          key={item.id}
          className={`group flex items-start gap-3 rounded-lg border p-3 transition-colors
            ${item.done ? "border-zinc-800/40 bg-zinc-900/20 opacity-60" : "border-zinc-800 bg-zinc-900/40 hover:border-zinc-700"}`}
        >
          <button onClick={() => toggle(item.id)} className="shrink-0 mt-0.5">
            {item.done ? (
              <CheckCircle2 className="size-4 text-emerald-500" />
            ) : (
              <Square className="size-4 text-zinc-600 hover:text-zinc-300 transition-colors" />
            )}
          </button>
          <div className="flex-1 min-w-0">
            <p className={`text-sm ${item.done ? "line-through text-zinc-600" : "text-zinc-300"}`}>
              {item.text}
            </p>
            {item.assignee && (
              <p className="text-[11px] text-zinc-600 mt-0.5">→ {item.assignee}</p>
            )}
          </div>
          <button
            onClick={() => remove(item.id)}
            className="opacity-0 group-hover:opacity-100 text-zinc-700 hover:text-zinc-400 transition-all shrink-0 mt-0.5"
          >
            <X className="size-3.5" />
          </button>
        </div>
      ))}

      {adding ? (
        <div className="flex flex-col gap-2 rounded-lg border border-zinc-700 bg-zinc-900 p-3 mt-1">
          <input
            autoFocus
            value={newText}
            onChange={(e) => setNewText(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") add(); if (e.key === "Escape") setAdding(false); }}
            placeholder="Describe the action item..."
            className="w-full bg-transparent text-sm text-zinc-100 placeholder:text-zinc-600 outline-none"
          />
          <input
            value={newAssignee}
            onChange={(e) => setNewAssignee(e.target.value)}
            placeholder="Assignee (optional)"
            className="w-full bg-transparent text-xs text-zinc-500 placeholder:text-zinc-700 outline-none border-t border-zinc-800 pt-2"
          />
          <div className="flex items-center justify-end gap-2 border-t border-zinc-800 pt-2">
            <button onClick={() => setAdding(false)} className="text-xs text-zinc-600 hover:text-zinc-400 px-2 py-1">Cancel</button>
            <button
              onClick={add}
              className="flex items-center gap-1.5 rounded-md border border-zinc-700 bg-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-100 hover:bg-zinc-700 transition-colors"
            >
              Add
            </button>
          </div>
        </div>
      ) : (
        <button
          onClick={() => setAdding(true)}
          className="flex items-center gap-1.5 rounded-lg border border-dashed border-zinc-800 p-3 text-xs text-zinc-600 hover:text-zinc-400 hover:border-zinc-700 transition-colors mt-1"
        >
          <Plus className="size-3.5" />
          Add action item
        </button>
      )}
    </div>
  );
}

// ─── Timeline event (read-only) ───────────────────────────────────────────────

function TimelineEvent({ event }) {
  const isSystem = event.type === "system";
  return (
    <div className="flex gap-3">
      <div className="flex flex-col items-center">
        <div className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[10px] font-bold
          ${isSystem ? "bg-zinc-800 text-zinc-500" : "bg-violet-900/80 text-violet-200"}`}>
          {isSystem ? <Zap className="size-3" /> : event.author}
        </div>
        <div className="mt-1 w-px flex-1 bg-zinc-800/60" />
      </div>
      <div className="pb-4 flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1 flex-wrap">
          {!isSystem && (
            <span className="text-xs font-semibold text-zinc-300">{event.name}</span>
          )}
          <span className="text-[11px] text-zinc-600">{event.time}</span>
          <span className={`ml-auto flex items-center gap-1 text-[10px] rounded px-1.5 py-0.5
            ${event.isPublic ? "bg-emerald-950/60 text-emerald-400" : "bg-zinc-800 text-zinc-500"}`}>
            {event.isPublic ? <Eye className="size-2.5" /> : <Lock className="size-2.5" />}
            {event.isPublic ? "Public" : "Internal"}
          </span>
        </div>
        <p className={`text-xs leading-relaxed ${isSystem ? "text-zinc-600 italic" : "text-zinc-400"}`}>
          {event.message}
        </p>
      </div>
    </div>
  );
}

// ─── AI Generate Button ───────────────────────────────────────────────────────

function AIGenerateBar({ onGenerate, loading, generated }) {
  return (
    <div className="rounded-lg border border-violet-900/50 bg-violet-950/20 p-4 flex items-center justify-between gap-4">
      <div className="flex items-center gap-3">
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-950/80 border border-violet-800/60 shrink-0">
          <Brain className="size-4 text-violet-400" />
        </div>
        <div>
          <p className="text-sm font-semibold text-zinc-200">
            {generated ? "Postmortem generated by AI" : "Generate with AI"}
          </p>
          <p className="text-[11px] text-zinc-500 mt-0.5">
            {generated
              ? "All sections were drafted from the incident timeline — edit freely"
              : "Claude will analyse the timeline and draft all sections automatically"}
          </p>
        </div>
      </div>
      <button
        onClick={onGenerate}
        disabled={loading}
        className={`flex items-center gap-2 rounded-md px-4 py-2 text-xs font-semibold shrink-0 transition-all duration-200
          ${loading
            ? "border border-zinc-700 bg-zinc-900 text-zinc-600 cursor-not-allowed"
            : generated
              ? "border border-zinc-700 bg-zinc-800 text-zinc-400 hover:bg-zinc-700 hover:text-zinc-200"
              : "border border-violet-700/60 bg-violet-950/60 text-violet-200 hover:bg-violet-900/60"
          }`}
      >
        {loading ? (
          <>
            <span className="animate-pulse">Generating...</span>
          </>
        ) : generated ? (
          <>
            <RefreshCw className="size-3.5" />
            Regenerate
          </>
        ) : (
          <>
            <Sparkles className="size-3.5" />
            Generate
          </>
        )}
      </button>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function Postmortem() {
  const { incidentId } = useParams();
  const navigate = useNavigate();

  // Use incidentId 3 as default (has postmortem data)
  const base = MOCK_POSTMORTEMS[incidentId] ?? MOCK_POSTMORTEMS[3];

  const [pm, setPm] = useState(base);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiGenerated, setAiGenerated] = useState(true); // already generated in mock

  const update = (field, value) => setPm((prev) => ({ ...prev, [field]: value }));

  const currentStatusIdx = STATUS_FLOW.indexOf(pm.status);
  const nextStatus = STATUS_FLOW[currentStatusIdx + 1];

  const handleAdvanceStatus = () => {
    if (!nextStatus) return;
    update("status", nextStatus);
  };

  const handleGenerate = () => {
    setAiLoading(true);
    setTimeout(() => {
      setAiLoading(false);
      setAiGenerated(true);
    }, 2200);
  };

  return (
    <div className="flex flex-col gap-0">

      {/* ── Back + actions bar ────────────────────────────────────────────── */}
      <div className="flex items-center justify-between gap-4 border-b border-zinc-800 pb-4 mb-6">
        <button
          onClick={() => navigate(`/dashboard/incidents/${pm.incidentId}`)}
          className="flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-200 transition-colors"
        >
          <ArrowLeft className="size-4" />
          Back to Incident
        </button>
        <div className="flex items-center gap-2">
          {/* Export */}
          <button className="flex items-center gap-2 rounded-md border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-xs font-medium text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200 transition-colors">
            <FileDown className="size-3.5" />
            Export
          </button>
          {/* Status advance */}
          {nextStatus && (
            <button
              onClick={handleAdvanceStatus}
              className={`flex items-center gap-2 rounded-md px-3 py-1.5 text-xs font-semibold transition-colors
                ${nextStatus === "Published"
                  ? "border border-emerald-800/60 bg-emerald-950/50 text-emerald-300 hover:bg-emerald-900/60"
                  : "border border-orange-800/60 bg-orange-950/50 text-orange-300 hover:bg-orange-900/60"
                }`}
            >
              <Send className="size-3.5" />
              Move to {nextStatus}
            </button>
          )}
        </div>
      </div>

      {/* ── Header ───────────────────────────────────────────────────────── */}
      <div className="mb-6 flex flex-col gap-3">
        {/* Title + status */}
        <div className="flex items-start gap-3 flex-wrap">
          <ScrollText className="size-5 text-zinc-600 mt-0.5 shrink-0" />
          <h1 className="text-2xl font-bold text-zinc-100 flex-1 leading-tight">
            Postmortem — {pm.title}
          </h1>
          <div className="flex items-center gap-2 shrink-0">
            <span className={`rounded-md px-2.5 py-1 text-xs font-bold ${severityClasses[pm.severity]}`}>
              {pm.severity}
            </span>
            <span className={`rounded-md px-2.5 py-1 text-xs font-semibold ${postmortemStatusClasses[pm.status]}`}>
              {pm.status}
            </span>
          </div>
        </div>

        {/* Status steps */}
        <div className="flex items-center gap-1 pl-7">
          {STATUS_FLOW.map((s, i) => {
            const done = i < currentStatusIdx;
            const active = i === currentStatusIdx;
            return (
              <div key={s} className="flex items-center gap-1">
                {i > 0 && <div className={`w-6 h-px ${done ? "bg-zinc-600" : "bg-zinc-800"}`} />}
                <div className={`flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold
                  ${active ? "bg-white/10 text-white border border-white/15" : done ? "text-zinc-500" : "text-zinc-700"}`}>
                  {done && <CheckCircle2 className="size-3 text-emerald-500" />}
                  {active && <span className="size-1.5 rounded-full bg-white" />}
                  {s}
                </div>
              </div>
            );
          })}
        </div>

        {/* Meta row */}
        <div className="flex flex-wrap items-center gap-5 text-xs text-zinc-500 pl-7">
          <span className="flex items-center gap-1.5">
            <Globe className="size-3" /> {pm.service}
          </span>
          <span className="flex items-center gap-1.5">
            <CalendarDays className="size-3" /> {pm.startedAt}
          </span>
          <span className="flex items-center gap-1.5 text-emerald-500">
            <CheckCircle2 className="size-3" /> Resolved: {pm.resolvedAt}
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="size-3" />
            <span className="font-mono">{pm.duration}</span>
            <span className="text-zinc-700">total duration</span>
          </span>
          <span className="flex items-center gap-1.5">
            <Users className="size-3" />
            Lead: <span className="text-zinc-300">{pm.lead.name}</span>
          </span>
        </div>
      </div>

      {/* ── Two-column layout ─────────────────────────────────────────────── */}
      <div className="flex flex-col xl:flex-row gap-5">

        {/* LEFT — document (65%) */}
        <div className="flex flex-col gap-4 xl:w-[65%]">

          {/* AI generate bar */}
          <AIGenerateBar
            onGenerate={handleGenerate}
            loading={aiLoading}
            generated={aiGenerated}
          />

          {/* Summary */}
          <Section icon={FileDown} title="Summary" defaultOpen={true}>
            <EditableBlock
              value={pm.summary}
              onChange={(v) => update("summary", v)}
              placeholder="Write a brief summary of what happened and how it was resolved..."
              rows={4}
            />
          </Section>

          {/* Root Cause */}
          <Section icon={Brain} iconClass="text-violet-400" title="Root Cause Analysis" badge={`${pm.rootCause.length} causes`}>
            <BulletListEditor
              items={pm.rootCause}
              onChange={(v) => update("rootCause", v)}
              icon={Brain}
              iconClass="text-violet-400"
              emptyLabel="No root causes identified yet. Click 'Add item' or generate with AI."
            />
          </Section>

          {/* Impact */}
          <Section icon={AlertTriangle} iconClass="text-orange-400" title="Impact">
            <EditableBlock
              value={pm.impact}
              onChange={(v) => update("impact", v)}
              placeholder="Describe who was affected, for how long, and what the business impact was..."
              rows={3}
            />
          </Section>

          {/* What went well */}
          <Section icon={ThumbsUp} iconClass="text-emerald-400" title="What Went Well" badge={`${pm.wentWell.length}`}>
            <BulletListEditor
              items={pm.wentWell}
              onChange={(v) => update("wentWell", v)}
              icon={CheckCircle2}
              iconClass="text-emerald-500"
              emptyLabel="Nothing noted yet."
            />
          </Section>

          {/* What went wrong */}
          <Section icon={ThumbsDown} iconClass="text-red-400" title="What Went Wrong" badge={`${pm.wentWrong.length}`}>
            <BulletListEditor
              items={pm.wentWrong}
              onChange={(v) => update("wentWrong", v)}
              icon={X}
              iconClass="text-red-400"
              emptyLabel="Nothing noted yet."
            />
          </Section>

          {/* Action Items */}
          <Section icon={CheckSquare} iconClass="text-blue-400" title="Action Items" badge={`${pm.actionItems.filter((t) => !t.done).length} open`}>
            <ActionItems
              items={pm.actionItems}
              onChange={(v) => update("actionItems", v)}
            />
          </Section>

        </div>

        {/* RIGHT — sidebar (35%) */}
        <div className="flex flex-col gap-4 xl:w-[35%]">

          {/* Incident meta card */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-wide border-b border-zinc-800 pb-2">
              Incident Details
            </h2>
            {[
              { label: "Incident ID", value: `INC-00${pm.incidentId}` },
              { label: "Service", value: pm.service },
              { label: "Severity", value: pm.severity },
              { label: "Started", value: pm.startedAt },
              { label: "Resolved", value: pm.resolvedAt },
              { label: "Duration", value: pm.duration },
            ].map(({ label, value }) => (
              <div key={label} className="flex items-center justify-between text-xs">
                <span className="text-zinc-600">{label}</span>
                <span className="text-zinc-300 font-medium font-mono text-right">{value}</span>
              </div>
            ))}
          </div>

          {/* Responders */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-wide border-b border-zinc-800 pb-2">
              Responders
            </h2>
            {pm.responders.map((r) => (
              <div key={r.initials} className="flex items-center gap-3">
                <div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${r.color}`}>
                  {r.initials}
                </div>
                <div className="flex-1">
                  <p className="text-xs font-medium text-zinc-200">{r.name}</p>
                  {r.initials === pm.lead.initials && (
                    <p className="text-[11px] text-zinc-600">Lead Responder</p>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Timeline (read-only) */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-800">
              <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">
                Incident Timeline
              </h2>
              <span className="text-[11px] text-zinc-700">{pm.timeline.length} events</span>
            </div>
            <div className="px-4 pt-4 max-h-72 overflow-y-auto">
              {pm.timeline.map((event) => (
                <TimelineEvent key={event.id} event={event} />
              ))}
            </div>
          </div>

          {/* Action items summary */}
          <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 flex flex-col gap-3">
            <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-wide border-b border-zinc-800 pb-2">
              Action Items Summary
            </h2>
            <div className="grid grid-cols-3 gap-2 text-center">
              <div className="rounded-lg bg-zinc-900 py-3">
                <p className="text-xl font-bold text-zinc-100">{pm.actionItems.length}</p>
                <p className="text-[11px] text-zinc-600 mt-0.5">Total</p>
              </div>
              <div className="rounded-lg bg-zinc-900 py-3">
                <p className="text-xl font-bold text-orange-400">{pm.actionItems.filter((t) => !t.done).length}</p>
                <p className="text-[11px] text-zinc-600 mt-0.5">Open</p>
              </div>
              <div className="rounded-lg bg-zinc-900 py-3">
                <p className="text-xl font-bold text-emerald-400">{pm.actionItems.filter((t) => t.done).length}</p>
                <p className="text-[11px] text-zinc-600 mt-0.5">Done</p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}